[theme]
base = "light"
primaryColor = "#008060"
backgroundColor = "#f6f6f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#202223"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 50
